### ISSUE TITLE
Communication and forks

### ISSUE THREAD

**Issue by gnanet** [gnanet/mailzu#1]
After seeng @crazy4chrissi fork, which addressed lot of things i have not discovered myself, i decided to open up tickets, to enable communication.

Also i consider to rename the default branch, to avoid using my nickname, and to avoid the propagation of it.

As the only one who also works on the code is @crazy4chrissi i would ask him for some ideas, how the default branch should be named

**Comment by gnanet** [comment]
I will test if everything works as expected from the gnafixes-mobile-crazy4chrissi branch and will merge it into gnafixes prior anything

**Comment by crazy4chrissi** [comment]
I don't care much about the branch name. We could just name it `gc` (g for gnanet and c for crazy4chrissi). mailzu-gc sounds good.

**Comment by gnanet** [comment]
i agree mailzu-gc ( it sounds also like  garbage-cleaned :D )

**Comment by crazy4chrissi** [comment]
I committed another change into my fork that adds a link to Virustotal to easily check attachments. It does not upload the attachment to virustotal, it just checks it based on its sha256.

I know I should finally merge with you and move to mailzu-gc branch....

**Comment by crazy4chrissi** [comment]
I merged your mailzu-gc together with my gnafixes branch into my (new) mailzu-gc branch.
I noticed we have a huge mess of tab versus space indention. Currently, some lines of the same file are space-indented (some 4, some 2 spaces) and some are tab indented.
We need to decide on one. I would vote for tabs. What do you think?

**Comment by gnanet** [comment]
If we can agree on 4space = 1tab i can arrange myself a pre processor, that convertsthis.

**Comment by gnanet** [comment]
After you merged my mailzu-gc branch, did you notice 3-4 commits of you were reverted? I did not had the time to apply 4 patches starting with privilege escalation fix, ending with omit warning in php7.

I would like to sync to your fork to properly include commits, and that way later changes can also be merged back to me easily. 

My first attempts to take changes from your fork and manually apply caused a bit logical issue for git, because the resulting code is the same, but the commits have not the same id, and so github thinks we are differ too much only by examining the amount of commits.

But actually i have no idea how to accomplish this goal ;)

**Comment by gnanet** [comment]
I think i found the docs about this, and some possible ways to resolve the merge conflicts the "github way" so we can start somewhere to exchange code and github can also follow the connection of these changes.

Notes to myself:
The article [about merge conflicts](https://help.github.com/articles/about-merge-conflicts/) details some simple resolutions.

But in case the merge fails because of more complex changes, they suggest [checking out pull requests locally](https://help.github.com/articles/checking-out-pull-requests-locally/)

**Comment by gnanet** [comment]
I will make some tests, which will include making pull requests from your fork to mine, and trying out the conflict resolution versions.

**Comment by crazy4chrissi** [comment]
Actually I tried pulling your fork into mine using a github pull request and ended up resolving the conflicts locally. I think I did not revert my changes in my mailzu-gc branch, everything should be merged.

Regarding the tabs and spaces: I know I voted for tabs but I now think spaces are better. Basically, because it is more common in PHP, because PEAR uses it, and because new people submitting changes tend to do it with spaces. And because I saw you doing your changes with spaces.
So I just ran it through the reformat option of my IDE. Simple replacement won't work as sometimes indention currently is 4 spaces, sometimes 2 spaces, sometimes 1 tab. The result is in this branch:
https://github.com/crazy4chrissi/mailzu/tree/mailzu-gc-reformatted

Do you like it or anything to complain?

**Comment by crazy4chrissi** [comment]
Regarding the pull requests and everything: We could also just start a mailzu-gc project on github and both commit to the same repository.

**Comment by gnanet** [comment]
Today i am in the office, so i only can react partially:
 - Tabs+Spaces -> i normally change _nanorc_ to **tabsize 4**, and **tabstospaces yes** where i work on code BUT :  I started using [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) at my repo of [Open Raspberry Pi Server Dashboard](https://github.com/gnanet/openrsd) which cleared a lot of other code-style issues too
- Push-Pull -> Same idea: I wanted to invite you as collaborator to one of my branches that we set as default (mailzu-gc ), but i wanted to reach consistent state with the merges and commits first

**Comment by gnanet** [comment]
I done a branch2branch merge, and created mailzu-gc-reformatted too, the code merge seemed to succeed, i only made a mistake in the order of commiting local changes prior fetching some change from github-origin, but its only a matter of commit order. But now we have a common branch that can receive PR-s if you develop something, also you can do a reverse PR to sync my changes to your fork.

**Comment by gnanet** [comment]
With the start of mailzu-ng this task is closed. The new rewrite supports PHP versions 7.2+ and it replaces PEAR/DB, and supersedes the forks here.
