### ISSUE TITLE
Class 'Auth' not found

### ISSUE THREAD

**Issue by Karel4** [gnanet/mailzu#15]
After hours of trial and error with pear install unmentioned plugins I cant get over AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'Auth' not found in ...

**Comment by gnanet** [comment]
Can you check if you did run `composer install` ? That should generate an autoloader, which in turn loads all the other classes.
Also please tell me what version of PHP you are using.

**Comment by gnanet** [comment]
Closing because no response in 1,5 months,
and because the error message points clearly, to the missed step for `composer install`

**Comment by Karel4** [comment]
> Can you check if you did run `composer install` ? That should generate an autoloader, which in turn loads all the other classes. Also please tell me what version of PHP you are using.

Haven't had it (composer) even installed. Also had missing php_imap. Now I got in.
