### ISSUE TITLE
LDAP TLS support + Languague support for Norwegian

### ISSUE THREAD

**Issue by thnilsen** [gnanet/mailzu#3]
Hi,
This is more if an FYI than an issue...

I've added LDAP TLS support to MailZu which might be of interest to others. My repo is at https://github.com/thnilsen/mailzu. 

The Norwegian translation still needs some more work.

**Comment by gnanet** [comment]
Yes i already been looking at your fork. could you reapply your changes to mailzu-gc-reformatted , and then open a pullrequest to me? I have no ldap currently to test, but i would  be happy to merge it.

**Comment by thnilsen** [comment]
Changes applied to the mailzu-gc-reformatted branch, and I've generated a pull request. Let me know if anything else is required.

The TLS change is up and running against an AD production environment.

**Comment by gnanet** [comment]
Great, ill get home in a couple of hours, and review them

**Comment by gnanet** [comment]
Merged #4
