### ISSUE TITLE
Which anti-virus detected the malware

### ISSUE THREAD

**Issue by toushin-taishi** [gnanet/mailzu#9]
Hi. First of all, thank you for such a wonderful amavisd-new quarantine tool which is quite indispensable on mail setups using amavisd-new for filtering. 
I would like to know if it's possible on a multi anti-virus engine configuration to identify which anti-virus detected the malware? Thanks!

**Comment by gnanet** [comment]
Only amavisd-new can give you the information you want, and the info has to be stored somehow into the database first, to be able to display it, so it is out of the scope of mailzu to "identify" the virus-scanner for a particular quarantine item.

I can only suggest you to open a ticket with your question at the amavisd-new project: https://gitlab.com/amavis/amavis/issues

If there is a way to get the info, they may also be able to help you on how you can insert that into the database.

**Please reopen this issue, if you already know how, and where that info will be stored in the database, and i can try to adapt mailzu to display it then**
